### ISSUE TITLE
Is the output shape same as the original pytorch HRNet which is (1,19,original_height/4, original_weight/4) ?

### ISSUE THREAD

**Issue by sakura-iv** [niecongchong/HRNet-keras-semantic-segmentation#3]
Hello, I am working on HRNet these days, and I found that in your test code, you use two images as one input to run the model, and it seems that you did not do the upsample process compared to original pytorch model. Because in the original model, for maintaining high resolution, the model's output shape is one fourth of the original image. And we have to do upsample process to make it be the original size. 
But in your code, I did not see this step, so I wonder how you build the model ? Are there some differences ? Besides, why do you put two images together into the model ?

**Comment by guillaumefrd** [comment]
In `final_layer()` method, there is an upsampling that is done on the concatenate.

**Comment by sakura-iv** [comment]
ok, thank you so much !
